import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[shell]
args = ["new-session", "-A", "-s", "default"]
program = "/opt/homebrew/bin/tmux"

[window]
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.padding]
x = 7
y = 0
